version: "3.9"

services:

  fastapi:

    build: .

    container_name: ai_incident_api

    ports:
      - "8000:8000"

    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama3.2:3b

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped